version: '3.3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: hermes
    user: root:node
    container_name: hermes
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_HOSTNAME=$POSTGRES_HOSTNAME
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "3333:$APP_PORT"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:5432 -- ./start.sh
    external_links:
      - db:db

  db:
    image: postgres:12
    env_file: .env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    stdin_open: true
    volumes:
      - ../pgdata:/var/lib/postgresql/data
      - ../dumps:/var/lib/postgresql/dumps
    tty: true
    ports:
      - 5432:5432/tcp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  node_modules:
